name: Deploy to GitHub Pages

on:
  # Löst den Workflow bei jedem Push in den master-Branch aus
  push:
    branches: [ master ]
  # Ermöglicht das manuelle Starten des Workflows über den "Actions"-Tab
  workflow_dispatch:

# Berechtigungen für das GITHUB_TOKEN festlegen
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish .NET Core Project
        run: dotnet publish MyWebsite/MyWebsite.csproj -c Release -o release --nologo

      # Basispfad für GitHub Pages anpassen
      - name: Change base-tag in index.html
        run: sed -i 's/<base href="\/" \/>/<base href="\/" \/>/g' release/wwwroot/index.html
      
      # .nojekyll-Datei hinzufügen
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll

      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Vom "release/wwwroot"-Verzeichnis hochladen
          path: 'release/wwwroot'

  # Bereitstellungs-Job
  deploy:
    # Hängt vom erfolgreichen Abschluss des "build"-Jobs ab
    needs: build
    
    # Berechtigungen für diesen spezifischen Job
    permissions:
      pages: write
      id-token: write
      
    # Auf der GitHub Pages-Umgebung bereitstellen
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4